---
title: "Untitled"
author: "Mengqi Chen & mc4396"
date: "10/27/2018"
output:
  html_document:
    df_print: paged
---

```{r}
# Data cleaning: remove the []
data <- read.csv("/Users/mengqichen/Documents/Github/GR5291Group8/Data/cleaned_movie_data.csv")
data$genres <- substr(data$genres, start = 2, stop=nchar(as.character(data$genres))-1)
data$production_companies <- substr(data$production_companies, start = 2, stop=nchar(as.character(data$production_companies))-1)
data$production_companies <- substr(data$production_companies, start = 2, stop=nchar(as.character(data$production_companies))-1)
data$keywords <- substr(data$keywords, start = 2, stop=nchar(as.character(data$keywords))-1)
```

## Wordcloud about directors
```{r, fig.height=1, fig.width=1}
library(tm)
library(wordcloud2)
library(RColorBrewer)
library(dplyr)
library(tidytext)
library(stringr)

dir <- as.data.frame(summary(data$director))
colnames(dir)[1] <- "frequency"
head(dir)
tail(dir) # there are many others exist and we need to remove them
dir$name <- rownames(dir)
dir <- dir[dir$name!='(Other)', ]
dir1 <- data.frame(dir$name,dir$frequency) # for drawing wordloud2, the 1st col is name, 2rd is frequency

wc <- wordcloud2(dir1,size=0.3,color=colorRampPalette(brewer.pal(9,"Set1"))(50))
# brewer.pal(12,'Set3')

library(webshot)
webshot::install_phantomjs()
# save it in html
library("htmlwidgets")
saveWidget(wc,"tmp.html",selfcontained = F)
# and in png
webshot("tmp.html","director.pdf", delay =10, vwidth = 680, vheight=480)
 
```

### Wordcloud about studios
```{r}
studio <- data$production_companies
studio1 <- c()
for (i in 1:length(studio)){
  studio1[i] <- strsplit(studio[i], ",")
}

studio11 <- unlist(studio1)
eee <- studio11[2]

pat <- "'"
studio_punct <- str_replace_all(studio11,pat,' ')
studio111 <- str_trim(studio_punct,side = 'both')
studio_df <- data.frame(table(studio111))
studio_df[which.max(studio_df$Freq),]
s <-studio_df[order(studio_df$Freq, decreasing = T),]
head(s,20)
dim(s)

s1 <- s[1:200,]
wc2 <- wordcloud2(s1, size = 0.3, color =colorRampPalette(brewer.pal(8,"Set1"))(20) )
saveWidget(wc2,"tmp.html",selfcontained = F)
# and in png
webshot("tmp.html","Studios.pdf", delay =10, vwidth = 680, vheight=480)
```

## Month and Year
```{r}
library(ggplot2)
plotTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 12,colour = "black",hjust=0.5),
    plot.subtitle = element_text(face="italic"),
    plot.caption = element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_line("grey80", size = 0.1),
    panel.grid.minor = element_blank(),
    strip.background = element_rect(fill = "grey80", color = "white"),
    strip.text = element_text(size=8),
    axis.title = element_text(size=10),
    axis.text = element_text(size=10),
    axis.title.x = element_text(hjust=1),
    axis.title.y = element_text(hjust=1),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(colour = "black", face = "bold"),
    legend.text = element_text(colour = "black", face = "bold"))
}

month <- data.frame(table(data$month))
colnames(month) <- c('Month', 'Times')
ggplot(data=month)+
  geom_bar(mapping = aes(x=Month, y=Times), stat = 'identity',fill = brewer.pal(12,'Set3') )+plotTheme()+labs(title = "Film's Release Months")+coord_polar()
ggsave("Film's Release Months", plot = last_plot(), path="/Users/mengqichen/Documents/Github/GR5291Group8/Result" , device='pdf')
```

## Release Years
```{r,warning=F}
ye <- data.frame(table(data$year))
dim(ye)
plot(ye)
which(ye$Var1 == '1969')
which(ye$Var1 == '1979')
which(ye$Var1 == '1989')
which(ye$Var1 == '1999')
which(ye$Var1 == '2009')
ye.60 <- sum(ye$Freq[1:36])
ye.70 <- sum(ye$Freq[37:46])
ye.80 <- sum(ye$Freq[47:56])
ye.90 <- sum(ye$Freq[57:66])
ye.00 <- sum(ye$Freq[67:76])
ye.10 <- sum(ye$Freq[77:83])
ye1 <- data.frame(c('1927-1969', '1970-1979', "1980-1989", "1990-1999", "2000-2009", '2010-2016'), c(ye.60, ye.70, ye.80, ye.90, ye.00, ye.10))
colnames(ye1) <- c('Years', "Number")
ggplot(data = ye1,mapping = aes(x=Years,y=Number))+
  geom_histogram(stat = 'identity', show.legend = T, fill=brewer.pal(6,'Set3'), bins = 0.4)+plotTheme()+coord_flip()+geom_text(label = ye1$Number, size=4, alpha =0.7,angle =356 )+labs(title = "Numbers of Films in Years")
ggsave("Numbers of Films in Years", plot = last_plot(), path="/Users/mengqichen/Documents/Github/GR5291Group8/Result" , device='pdf')
```

## Genra by years (eliminate former time)
```{r}

```

## Runtime of movie
```{r}
ggplot(data,mapping = aes(data$runtime))+
  geom_bar(stat = 'count',fill=colorRampPalette(brewer.pal(11,"Spectral"))(130))+plotTheme()+labs(x="Runtime", y= 'Frequency', title = "Runtimes of Films")
ggsave("Runtimes of Films", plot = last_plot(), path="/Users/mengqichen/Documents/Github/GR5291Group8/Result" , device='pdf')
```

## Budget
```{r}
bud <- data$budget
bud <- bud[bud!=0]
bud <- data.frame(bud/1000000)
ggplot(bud,mapping = aes(bud))+
  geom_histogram(fill=colorRampPalette(brewer.pal(8,"Spectral"))(100), bins = 100)+plotTheme()+labs(x="Budget(10^6)", y= 'Frequency', title = "Budgets of Films")
ggsave("Budgets of Films", plot = last_plot(), path="/Users/mengqichen/Documents/Github/GR5291Group8/Result" , device='pdf')
```

## Vote Average
```{r}
ggplot(data,mapping = aes(data$vote_average))+
  geom_bar(stat = 'count',fill=colorRampPalette(brewer.pal(3,"Paired"))(56))+plotTheme()+labs(x="Vote_Average", y= 'Frequency', title = "Vote_average of Films")
ggsave("Vote_average of Films", plot = last_plot(), path="/Users/mengqichen/Documents/Github/GR5291Group8/Result" , device='pdf')
```

## Popularity
```{r}
pop <- data$popularity
pop <- pop[pop!=0]
hist(pop)
ggplot(as.data.frame(pop),mapping = aes(pop))+
  geom_histogram(fill=colorRampPalette(brewer.pal(4,"PRGn"))(100), bins = 100)+plotTheme()+labs( title = "Popularity of Films")+xlim(0,200)
ggsave("Popularity of Films", plot = last_plot(), path="/Users/mengqichen/Documents/Github/GR5291Group8/Result" , device='pdf')
```

## Revenue
```{r}
re <- data$revenue
hist(re)
ggplot(as.data.frame(re/1000000),mapping = aes(re))+
  geom_histogram(fill=colorRampPalette(brewer.pal(4,"RdGy"))(100), bins = 100)+plotTheme()+labs( x='Revenue(10^6)',title = "Revenue of Films")
ggsave("Revenue of Films", plot = last_plot(), path="/Users/mengqichen/Documents/Github/GR5291Group8/Result" , device='pdf')
```
## Return Rate
```{r}
rate <- data$revenue/data$budget
ggplot(as.data.frame(rate),mapping = aes(rate))+
  geom_histogram( fill=colorRampPalette(brewer.pal(8,"Spectral"))(100), bins =100 )+plotTheme()+labs( x='Return Rate',title = "Return Rate of Films")+ xlim(0,50)
ggsave("Return Rate of Films", plot = last_plot(), path="/Users/mengqichen/Documents/Github/GR5291Group8/Result" , device='pdf')
```

